{% set name = "dustmaps" %}
{% set version = "1.0.14" %}
{% set sha256 = "51347809dcd186d14c4f88c7856bb11a931bc422e8f57774e9c90d19e76c43cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - astropy-base
    - h5py
    - healpy
    - requests
    - progressbar2
    - six

test:
  imports:
    - dustmaps

about:
  home: https://github.com/gregreen/dustmaps
  license: GPL-2.0-or-later
  license_file: LICENSE.txt
  summary: A uniform interface for a number of 2D and 3D maps of interstellar dust reddening/extinction.
  doc_url: http://dustmaps.readthedocs.io/
  dev_url: https://github.com/gregreen/dustmaps

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
