{% set name = "dustmaps" %}
{% set version = "1.0.4" %}
{% set sha256 = "5d5d06e016ee914f55eecf0e4e5eabd74648bc2880ef7997568be329bad4b4a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - astropy
    - h5py
    - healpy
    - requests
    - progressbar2
    - six

test:
  imports:
    - dustmaps

about:
  home: https://github.com/gregreen/dustmaps
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: 'A uniform interface for a number of 2D and 3D maps of interstellar dust reddening/extinction.'
  doc_url: http://dustmaps.readthedocs.io/
  dev_url: https://github.com/gregreen/dustmaps

extra:
  recipe-maintainers:
    - guillochon
    - pkgw
