# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SA2aymIjNLgfF7jCbo9XrgdYbc6Ctm/lsn5ENfHSNPbUU6bxumvWPskTJKj7dsn2adL95YqohjESfblSVUuKyfM4nc0U0shISsuXc0FvWGNzRF9KdaA5GNjafrKzCoXIVWZfKjScEVK7I5NxXTwOZBXFQiMWAllKoCY009wKKH8XtbCMA6FevLzgKxyzBi0FxNTbuaD79FJsALqjNWB/vBgD1mU0EXweXaoux3UQXsUudQhimSwQTb/IfzL9VDH6owyK+DD/80z7V12L0HXETssaatVWV79pRv9RVpAqwN0wePqCEzhXQ84hm1nB+31gb/LIhicUaJ9JBTFl/8nV1jNt0kZKqXV058UjbgBZPDTQmu4XNwmAzhpYOwmCXMTNKByOb5Wp9sIyLkgYEVH8P5Xd8ERQSZhHEXbLDmGF5N4lF121BJ1WWdgHOZzCeARDIFcZNn2P2lm2SB0rhLgtAVsPEQuGY4Of7tDm/BuUVoznhvmVdWDoJb2/LDcDABf+MyKJLmV2gOLFjtM0mVzXLEaYkcyb8iejWCe1XrtHYIs8D3WFqm16L0Adee1ZX4NGS87ShJbTOeL0+h8GMo//9cUtnRSd5DfO1PxP6DP68u+H5hyQ3y8fRVzSeBR1mtJH0wjN7WOeYlyFd0aQo6o+sfHamLFTRmQAZYpvXpmHrUk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
