appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: SA2aymIjNLgfF7jCbo9XrgdYbc6Ctm/lsn5ENfHSNPbUU6bxumvWPskTJKj7dsn2adL95YqohjESfblSVUuKyfM4nc0U0shISsuXc0FvWGNzRF9KdaA5GNjafrKzCoXIVWZfKjScEVK7I5NxXTwOZBXFQiMWAllKoCY009wKKH8XtbCMA6FevLzgKxyzBi0FxNTbuaD79FJsALqjNWB/vBgD1mU0EXweXaoux3UQXsUudQhimSwQTb/IfzL9VDH6owyK+DD/80z7V12L0HXETssaatVWV79pRv9RVpAqwN0wePqCEzhXQ84hm1nB+31gb/LIhicUaJ9JBTFl/8nV1jNt0kZKqXV058UjbgBZPDTQmu4XNwmAzhpYOwmCXMTNKByOb5Wp9sIyLkgYEVH8P5Xd8ERQSZhHEXbLDmGF5N4lF121BJ1WWdgHOZzCeARDIFcZNn2P2lm2SB0rhLgtAVsPEQuGY4Of7tDm/BuUVoznhvmVdWDoJb2/LDcDABf+MyKJLmV2gOLFjtM0mVzXLEaYkcyb8iejWCe1XrtHYIs8D3WFqm16L0Adee1ZX4NGS87ShJbTOeL0+h8GMo//9cUtnRSd5DfO1PxP6DP68u+H5hyQ3y8fRVzSeBR1mtJH0wjN7WOeYlyFd0aQo6o+sfHamLFTRmQAZYpvXpmHrUk=}
conda_forge_output_validation: true
